apiVersion: apps/v1
kind: Deployment
metadata:
  name: Springboot-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Springboot-tutorial
  template:
    metadata:
      labels:
        app: Springboot-tutorial
    spec:
      containers:
        - name: app
          image: xinyan272/spring-tutorial:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3