apiVersion: v1 
kind: Service 
metadata: 
  name: Springboot-tutorial
spec:
  selector:
    app: Springboot-tutorial
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: ClusterIP